#Using .env file
version: '3'

services:
  app:
    build: .
    image: ${SERVER_IMAGE}
    restart: always
    container_name: my-app
    ports:
      - ${SERVER_PORT}
    environment: #environment of strapi 
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=false
    depends_on:
      - db
    
  db:
    image: postgres:latest
    restart: always
    container_name: my-db
    ports:
      - ${DB_PORTS}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  